### ISSUE TITLE
Unable to install from source

### ISSUE THREAD

**Issue by cosmincc** [Annihil/revolut-emergency#15]
I've tried on different platforms (Ubuntu linux 20 and MacOs) and get a similar error:
```
revolut-emergency$ npm install
revolut-emergency$ npm start

> r-emergency@6.3.0 start /Users/cosminc/revolut-emergency
> concurrently "cross-env EXTEND_ESLINT=true BROWSER=none yarn react-start" "wait-on http://localhost:3000 && cross-env DEV=1 electron ."

[0] events.js:291
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: spawn yarn ENOENT
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
[0]     at onErrorNT (internal/child_process.js:468:16)
[0]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[0] Emitted 'error' event on ChildProcess instance at:
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
[0]     at onErrorNT (internal/child_process.js:468:16)
[0]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[0]   errno: -2,
[0]   code: 'ENOENT',
[0]   syscall: 'spawn yarn',
[0]   path: 'yarn',
[0]   spawnargs: [ 'react-start' ]
[0] }
[0] cross-env EXTEND_ESLINT=true BROWSER=none yarn react-start exited with code 1

[1] wait-on http://localhost:3000 && cross-env DEV=1 electron . exited with code SIGINT
```

**Comment by Mizperix** [comment]
I have a very similiar error to this on Windows10, unfortunately I could not figure out a solution to this.

```
> r-emergency@6.3.0 start E:\Revolut
> concurrently "cross-env EXTEND_ESLINT=true BROWSER=none yarn react-start" "wait-on http://localhost:3000 && cross-env DEV=1 electron ."

[0] 'yarn' is not recognized as an internal or external command,
[0] operable program or batch file.
[0] events.js:287
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: spawn yarn ENOENT
[0]     at notFoundError (E:\Revolut\node_modules\cross-spawn\lib\enoent.js:6:26)
[0]     at verifyENOENT (E:\Revolut\node_modules\cross-spawn\lib\enoent.js:40:16)
[0]     at ChildProcess.cp.emit (E:\Revolut\node_modules\cross-spawn\lib\enoent.js:27:25)
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0] Emitted 'error' event on ChildProcess instance at:
[0]     at ChildProcess.cp.emit (E:\Revolut\node_modules\cross-spawn\lib\enoent.js:30:37)
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
[0]   code: 'ENOENT',
[0]   errno: 'ENOENT',
[0]   syscall: 'spawn yarn',
[0]   path: 'yarn',
[0]   spawnargs: [ 'react-start' ]
[0] }
[0] cross-env EXTEND_ESLINT=true BROWSER=none yarn react-start exited with code 1
```
